[programs.localnet]
rs_staking_program = "6RhXNaW1oQYQmjTc1ypb4bEFe1QasPAgEfFNhQ3HnSqo"

[programs.devnet]
rs_staking_program = "6RhXNaW1oQYQmjTc1ypb4bEFe1QasPAgEfFNhQ3HnSqo"

[registry]
url = "https://anchor.projectserum.com"

[provider]

cluster = "devnet"
#cluster = "http://127.0.0.1:8899"
#wallet = "/home/gitpod/.config/solana/id.json"
wallet = "/kg/solana/kg_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
